Attribute VB_Name = "Performance_Payloads_"
Option Explicit

' =============================================================================
' Module:      Performance_Payloads_
' Project:     ModernJsonInVBA (workbook tooling, not part of the library)
'
' Runs the library against the large payloads in json_payloads\ and prints a
' markdown performance report to the Immediate window (Ctrl+G) - paste it
' straight into GitHub.
'
' Usage:
'   Run_JsonPerfSuite                    ' all payloads, default folder
'   Run_JsonPerfSuite "C:\other\folder"  ' explicit folder
'
' Per payload: file read, Json_Parse (model), Json_Stringify, table upsert
' via Excel_UpsertListObjectFromJsonAtRoot (create + refresh), and
' Excel_ListObjectToJson export. Payloads with "nested" in the file name
' upsert with nonTableArraysAsJson:=True so array columns are included.
'
' Payloads are generated by json_payloads\generate_payloads.py (deterministic,
' pure ASCII), so numbers are comparable across runs and machines.
' =============================================================================

Public Sub Run_JsonPerfSuite(Optional ByVal folderPath As String = vbNullString)
    Debug.Print JsonPerfReport(folderPath)
End Sub

' Build the full markdown report. Kept separate from Run_JsonPerfSuite so
' automation can fetch the text via Application.Run.
Public Function JsonPerfReport(Optional ByVal folderPath As String = vbNullString) As String
    If Len(folderPath) = 0 Then
        folderPath = ThisWorkbook.path & Application.PathSeparator & "json_payloads"
    End If

    Dim md As JsonTextBuilder
    JsonSB_Init md, 8192

    PP_Append md, "# ModernJsonInVBA Performance Report"
    PP_Append md, ""
    PP_Append md, "- Generated: " & Format$(Now, "yyyy-mm-dd hh:nn:ss")

    #If Win64 Then
        PP_Append md, "- Excel " & Application.Version & " (64-bit VBA)"
    #Else
        PP_Append md, "- Excel " & Application.Version & " (32-bit VBA)"
    #End If

    PP_Append md, "- Payload folder: " & folderPath
    PP_Append md, "- Ops: file read, Json_Parse (model), Json_Stringify, upsert create/refresh (Excel_UpsertListObjectFromJsonAtRoot), export (Excel_ListObjectToJson)"

    ' ---- discover payloads ----
    Dim files() As String
    Dim fileCount As Long
    fileCount = 0

    Dim f As String
    f = Dir(folderPath & Application.PathSeparator & "*.json")

    Do While Len(f) > 0
        fileCount = fileCount + 1
        If fileCount = 1 Then
            ReDim files(1 To 16) As String
        ElseIf fileCount > UBound(files) Then
            ReDim Preserve files(1 To UBound(files) * 2) As String
        End If
        files(fileCount) = f
        f = Dir
    Loop

    If fileCount = 0 Then
        PP_Append md, ""
        PP_Append md, "**No .json payloads found.** Run json_payloads\generate_payloads.py first."
        JsonPerfReport = JsonSB_Text(md)
        Exit Function
    End If

    ' Stable report order.
    PP_SortNames files, fileCount

    ' ---- suite-level application state ----
    Dim calcOld As XlCalculation
    Dim eventsOld As Boolean
    Dim updatingOld As Boolean

    calcOld = Application.Calculation
    eventsOld = Application.EnableEvents
    updatingOld = Application.ScreenUpdating

    Application.ScreenUpdating = False
    Application.EnableEvents = False
    Application.Calculation = xlCalculationManual

    Dim suiteStart As Double
    suiteStart = Timer

    Dim i As Long
    For i = 1 To fileCount
        PP_OnePayload md, folderPath & Application.PathSeparator & files(i), files(i)
    Next i

    PP_Append md, ""
    PP_Append md, "Total suite time: " & Format$(PP_Elapsed(suiteStart), "0.0") & " s"

    Application.Calculation = calcOld
    Application.EnableEvents = eventsOld
    Application.ScreenUpdating = updatingOld

    JsonPerfReport = JsonSB_Text(md)
End Function

' =============================================================================
' Internals
' =============================================================================

Private Sub PP_OnePayload(ByRef md As JsonTextBuilder, ByVal filePath As String, ByVal fileName As String)
    Dim stage As String
    On Error GoTo Fail

    Dim fileMB As Double
    fileMB = FileLen(filePath) / 1048576#

    PP_Append md, ""
    PP_Append md, "### " & fileName & " - " & Format$(fileMB, "0.0") & " MB"
    PP_Append md, ""
    PP_Append md, "| Operation | Seconds | Throughput / detail |"
    PP_Append md, "|---|---:|---|"

    Dim t0 As Double
    Dim secs As Double

    ' ---- file read ----
    stage = "file read"
    t0 = Timer

    Dim h As Integer
    h = FreeFile

    Dim jsonText As String
    Open filePath For Input As #h
    jsonText = Input$(LOF(h), h)
    Close #h

    secs = PP_Elapsed(t0)
    PP_Row md, "Read file", secs, PP_Rate(fileMB, secs, "MB/s")

    ' ---- parse to model ----
    stage = "Json_Parse"
    t0 = Timer

    Dim parsed As Variant
    Json_ParseInto jsonText, parsed

    secs = PP_Elapsed(t0)
    PP_Row md, "Json_Parse (model)", secs, PP_Rate(fileMB, secs, "MB/s")

    ' ---- stringify from model ----
    stage = "Json_Stringify"
    t0 = Timer

    Dim js As String
    js = Json_Stringify(parsed)

    secs = PP_Elapsed(t0)
    PP_Row md, "Json_Stringify", secs, _
        PP_Rate(Len(js) / 1048576#, secs, "MB/s") & " (" & Format$(Len(js), "#,##0") & " chars)"

    js = vbNullString
    Set parsed = Nothing

    ' ---- upsert create / refresh ----
    Dim arraysAsJson As Boolean
    arraysAsJson = (InStr(1, fileName, "nested", vbTextCompare) > 0)

    Dim ws As Worksheet
    Set ws = ThisWorkbook.Worksheets.Add

    stage = "upsert create"
    t0 = Timer
    Excel_UpsertListObjectFromJsonAtRoot ws, "tPerf", ws.Range("A1"), jsonText, "$", _
        nonTableArraysAsJson:=arraysAsJson
    secs = PP_Elapsed(t0)

    Dim lo As ListObject
    Set lo = ws.ListObjects("tPerf")

    Dim rowsN As Long
    Dim colsN As Long
    rowsN = lo.ListRows.count
    colsN = lo.ListColumns.count

    PP_Row md, "Upsert create (" & Format$(rowsN, "#,##0") & " rows x " & colsN & " cols)", _
        secs, PP_Rate(rowsN, secs, "rows/s")

    stage = "upsert refresh"
    t0 = Timer
    Excel_UpsertListObjectFromJsonAtRoot ws, "tPerf", ws.Range("A1"), jsonText, "$", _
        nonTableArraysAsJson:=arraysAsJson
    secs = PP_Elapsed(t0)
    PP_Row md, "Upsert refresh", secs, PP_Rate(rowsN, secs, "rows/s")

    jsonText = vbNullString

    ' ---- export ----
    stage = "export"
    t0 = Timer

    Dim exported As String
    exported = Excel_ListObjectToJson(lo)

    secs = PP_Elapsed(t0)
    PP_Row md, "Table -> JSON export", secs, _
        PP_Rate(Len(exported) / 1048576#, secs, "MB/s") & " (" & Format$(Len(exported), "#,##0") & " chars)"

    exported = vbNullString

    PP_DeleteSheet ws
    Exit Sub

Fail:
    Dim errText As String
    errText = "ERROR during " & stage & ": " & Err.Number & " - " & Err.Description

    PP_Append md, "| " & errText & " | | |"

    On Error Resume Next
    PP_DeleteSheet ws
    Close
End Sub

Private Sub PP_DeleteSheet(ByVal ws As Worksheet)
    If ws Is Nothing Then Exit Sub

    Dim alertsOld As Boolean
    alertsOld = Application.DisplayAlerts
    Application.DisplayAlerts = False
    ws.Delete
    Application.DisplayAlerts = alertsOld
End Sub

Private Sub PP_Row(ByRef md As JsonTextBuilder, ByVal op As String, ByVal secs As Double, ByVal detail As String)
    PP_Append md, "| " & op & " | " & Format$(secs, "0.000") & " | " & detail & " |"
End Sub

Private Function PP_Rate(ByVal amount As Double, ByVal secs As Double, ByVal unit As String) As String
    If secs <= 0 Then
        PP_Rate = "-"
    Else
        PP_Rate = Format$(amount / secs, "#,##0") & " " & unit
    End If
End Function

' Timer with midnight wrap protection.
Private Function PP_Elapsed(ByVal t0 As Double) As Double
    Dim t1 As Double
    t1 = Timer
    If t1 < t0 Then t1 = t1 + 86400#
    PP_Elapsed = t1 - t0
End Function

Private Sub PP_Append(ByRef md As JsonTextBuilder, ByVal line As String)
    JsonSB_Append md, line
    JsonSB_Append md, vbCrLf
End Sub

' Insertion sort (file lists are tiny).
Private Sub PP_SortNames(ByRef names() As String, ByVal count As Long)
    Dim i As Long
    Dim j As Long

    For i = 2 To count
        Dim current As String
        current = names(i)

        j = i - 1
        Do While j >= 1
            If StrComp(names(j), current, vbTextCompare) <= 0 Then Exit Do
            names(j + 1) = names(j)
            j = j - 1
        Loop

        names(j + 1) = current
    Next i
End Sub
